# Generated by Django 5.1.5 on 2025-02-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant'),
        ),
    ]
