# Generated by Django 5.1.5 on 2025-01-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='info',
            new_name='data',
        ),
    ]
