# Generated by Django 5.1.6 on 2025-02-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_garden_plant_sensordata_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
