# Generated by Django 5.1.5 on 2025-02-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_plant_hardware_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('preferred_light', models.FloatField()),
                ('min_light', models.FloatField()),
                ('max_light', models.FloatField()),
                ('preferred_soil_moisture', models.FloatField()),
                ('min_soil_moisture', models.FloatField()),
                ('max_soil_moisture', models.FloatField()),
                ('preferred_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('preferred_humidity', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='optimal_humidity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='optimal_light',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='optimal_soil_moisture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='optimal_temperature',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.AddField(
            model_name='plant',
            name='houseplant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.houseplant'),
        ),
    ]
