# Generated by Django 5.1.5 on 2025-02-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('main', '0006_plant_hardware_id'),
    ]

    operations = [
    ]
