# Generated by Django 5.1.5 on 2025-02-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_houseplant_remove_plant_optimal_humidity_and_more'),
        ('main', '0007_merge_0002_initial_0006_plant_hardware_id'),
    ]

    operations = [
    ]
