# Generated by Django 5.1.5 on 2025-03-06 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_garden_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_streak_increment', models.DateTimeField(default=django.utils.timezone.now)),
                ('streak', models.PositiveIntegerField(default=1)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'garden')},
            },
        ),
    ]
