# Generated by Django 5.1.5 on 2025-03-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20250228_2331'),
        ('main', '0009_alter_garden_user'),
    ]

    operations = [
    ]
