# Generated by Django 5.1.5 on 2025-03-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_gardenvisit'),
        ('main', '0010_merge_0008_merge_20250228_2331_0009_alter_garden_user'),
    ]

    operations = [
    ]
